### PR TITLE
Ignition 8 DEV

### PR DESCRIPTION
**Pull request by TomKimsey**
code improvements based on some testing I did today.

### CODE REVIEW

**Comment by alexjhawk** [comment]
One thing I picked up on here is that the Ewon brand here should be just Ewon, not eWon/eWON/etc. I talked to Julia today about the Ignition Demo, and that was one of her comments.

**Comment by TomKimsey** [comment]
> One thing I picked up on here is that the Ewon brand here should be just Ewon, not eWon/eWON/etc. I talked to Julia today about the Ignition Demo, and that was one of her comments.
> 
> I didn't want to hold up this PR though, since that doesn't really have anything to do with this PR necessarily.

I can probably do a PR sometime soon to adjust all the branding.

**Comment by alexjhawk** [comment]
> > One thing I picked up on here is that the Ewon brand here should be just Ewon, not eWon/eWON/etc. I talked to Julia today about the Ignition Demo, and that was one of her comments.
> > I didn't want to hold up this PR though, since that doesn't really have anything to do with this PR necessarily.
> 
> I can probably do a PR sometime soon to adjust all the branding.

https://github.com/hms-networks/eWonConnector/tree/Ignition-8-EwonNameFix

I changed the branding in all of the places I found appropriate. I'm not sure if I missed anything though. I only focused on changing things that were outward-facing, to avoid creating any code problems.

**Comment by TomKimsey** [comment]
@alexjhawk if you want to make a PR for that ill review today.  I think those commits can get squashed into one commit since its just a global refactor

**Pull request merged**
